apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kafka-to-influxdb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kafka-to-influxdb
    app.kubernetes.io/part-of: kafka-to-influxdb
  name: kafka-to-influxdb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kafka-to-influxdb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kafka-to-influxdb
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhpds-cloud-tenant/kafka-to-influxdb/kafka-to-influxdb@sha256:8448004c3bab057a08afbf8ff422d7fd45aef7d63957d96646916573950732f0
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
