apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kafka-to-influxdb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhpds-cloud-tenant/kafka-to-influxdb/kafka-to-influxdb@sha256:8448004c3bab057a08afbf8ff422d7fd45aef7d63957d96646916573950732f0
        name: container-image
        resources: {}
status: {}
